import type { CouplePosterTemplate } from '../types'

export const winterMomentsChat: CouplePosterTemplate = {
  id: 'winter-moments-chat',
  name: '冬日甜甜展示',
  category: '小红书发布图',
  thumbnail: '',
  canvasWidth: 1080,
  canvasHeight: 1120,
  backgroundColor: '#ffffff',
  elements: [
    { id: 'top-bar', type: 'shape', shape: 'rectangle', x: 0, y: 0, width: 1080, height: 112, fill: '#ffffff', zIndex: 1 },
    { id: 'top-avatar', type: 'image', source: 'avatarA', x: 126, y: 30, width: 58, height: 58, shape: 'circle', borderWidth: 2, borderColor: '#ffffff', shadowColor: 'rgba(0,0,0,0.16)', shadowBlur: 12, shadowOffsetY: 5, objectFit: 'cover', zIndex: 3 },
    { id: 'account', type: 'text', text: 'Biscuit', x: 208, y: 35, width: 360, fontSize: 38, fontFamily: '"Comic Sans MS", "Trebuchet MS", sans-serif', fontWeight: 700, color: '#171717', textAlign: 'left', editable: true, zIndex: 3 },
    { id: 'top-note', type: 'text', text: '头像工坊', x: 770, y: 42, width: 180, fontSize: 25, fontFamily: 'YouYuan, "Microsoft YaHei", sans-serif', fontWeight: 700, color: '#8a8a8a', textAlign: 'right', editable: true, zIndex: 3 },
    { id: 'green-band', type: 'shape', shape: 'rectangle', x: 0, y: 112, width: 1080, height: 330, fill: '#0b6b42', zIndex: 1 },
    { id: 'white-band', type: 'shape', shape: 'rectangle', x: 0, y: 442, width: 1080, height: 410, fill: '#ffffff', zIndex: 1 },
    { id: 'circle-a', type: 'image', source: 'avatarA', x: 110, y: 250, width: 380, height: 380, shape: 'circle', borderWidth: 10, borderColor: '#ffffff', shadowColor: 'rgba(0,0,0,0.16)', shadowBlur: 22, shadowOffsetY: 12, objectFit: 'cover', zIndex: 3 },
    { id: 'circle-b', type: 'image', source: 'avatarB', x: 585, y: 250, width: 380, height: 380, shape: 'circle', borderWidth: 10, borderColor: '#ffffff', shadowColor: 'rgba(0,0,0,0.16)', shadowBlur: 22, shadowOffsetY: 12, objectFit: 'cover', zIndex: 3 },
    { id: 'small-a', type: 'image', source: 'avatarA', x: 150, y: 690, width: 150, height: 150, shape: 'rounded-rectangle', borderRadius: 18, borderWidth: 3, borderColor: '#ffffff', shadowColor: 'rgba(0,0,0,0.18)', shadowBlur: 16, shadowOffsetY: 9, objectFit: 'cover', zIndex: 4 },
    { id: 'bubble-a', type: 'shape', shape: 'rectangle', x: 350, y: 690, width: 380, height: 76, fill: '#f1f1f1', borderRadius: 38, shadowColor: 'rgba(0,0,0,0.06)', shadowBlur: 8, shadowOffsetY: 4, zIndex: 2 },
    { id: 'bubble-text-a', type: 'text', text: 'Biscuit', x: 350, y: 712, width: 380, fontSize: 30, fontFamily: '"Microsoft YaHei", sans-serif', fontWeight: 700, color: '#171717', textAlign: 'center', editable: true, zIndex: 3 },
    { id: 'small-b', type: 'image', source: 'avatarB', x: 780, y: 798, width: 150, height: 150, shape: 'rounded-rectangle', borderRadius: 18, borderWidth: 3, borderColor: '#ffffff', shadowColor: 'rgba(0,0,0,0.18)', shadowBlur: 16, shadowOffsetY: 9, objectFit: 'cover', zIndex: 4 },
    { id: 'bubble-b', type: 'shape', shape: 'rectangle', x: 390, y: 820, width: 380, height: 76, fill: '#f1f1f1', borderRadius: 38, shadowColor: 'rgba(0,0,0,0.06)', shadowBlur: 8, shadowOffsetY: 4, zIndex: 2 },
    { id: 'bubble-text-b', type: 'text', text: '一丁点甜', x: 390, y: 842, width: 380, fontSize: 30, fontFamily: '"Microsoft YaHei", sans-serif', fontWeight: 700, color: '#171717', textAlign: 'center', editable: true, zIndex: 3 },
    { id: 'pager-a', type: 'shape', shape: 'circle', x: 486, y: 970, width: 16, height: 16, fill: '#ff335c', zIndex: 5 },
    { id: 'pager-b', type: 'shape', shape: 'circle', x: 516, y: 970, width: 16, height: 16, fill: '#d8d8d8', zIndex: 5 },
    { id: 'pager-c', type: 'shape', shape: 'circle', x: 546, y: 970, width: 16, height: 16, fill: '#d8d8d8', zIndex: 5 },
    { id: 'title', type: 'text', text: '是生活里的一丁点甜', x: 70, y: 1018, width: 940, fontSize: 38, fontFamily: '"Microsoft YaHei", sans-serif', fontWeight: 700, color: '#333333', textAlign: 'center', editable: true, zIndex: 5 },
  ],
}
